name: TicketManager
main: net.dawn.mc.micheldewit.plugin.Modreq
version: 1.3.2
author: Micheldewit
softdepends: []
description: Serverside Ticketmanager, goes in coop with TicketMan-Web services.

commands:
   ticket:
     description: Ticket management command.

permissions:
  TicketManager.Staff:
    description: Grants access to all TicketManager Permissions.

